# LOCAL SEARCH

In [3]:
import random
import numpy as np
import itertools
from functions import *
import time

## Utility function and Min-conflicts algorithm

I mainly changed the else statemnt in min_conflicts
but I also changed the parameter orders because it was confusing me

In [148]:
def UTILITYFUNCT(B,lettersdict,lettersB):
    N=np.shape(B)[0]
    R=0
    C=0
    L=0
    Z=0
    for i in range(N):
        for j in range(N):
            if not check_no_zero([i,j],B):
                Z=Z+1
    for i in range(N):
        if not row_checker(i,B):
            R=R+1
    for j in range(N):
        if not column_checker(j,B):
            C=C+1
    for i in range(N):
        for j in range(N):
            if not letter_check([i,j],B,lettersB,lettersdict):
                L=L+1
    #N* R,C because they are worth more than Z,L
    U=N*(R+C)+Z+L
    return U
#INPUTS: INITIAL MATRIX CURRENT, LETTERS OF THE CURRENT,LETTERS DIC
def min_conflicts(lettersdict,lettersCURRENT):
    dim=len(lettersCURRENT)
    CURRENT=np.array([[0]*dim for i in range(dim)])
    choices,to_start=get_choices_letters(CURRENT,lettersdict)
    #CURRENT is the VALUES OF THE MATRIX
    iterat=0
    for row in range(0,len(choices)):
        for col in range(0,len(choices)):
            CURRENT[row,col]=0
    #UTILITY FUNCTION U
    A=CURRENT
    U=UTILITYFUNCT(CURRENT,lettersdict,lettersCURRENT)
    UA=U
    # is the value at the most constranted location 
    cur=0

    while True:
        iterat=iterat+1
        #check if its done
        if U==0:
            return CURRENT,iterat
        else:
            j=int(to_start[cur][0][0])
            k=int(to_start[cur][0][1])
            A=CURRENT
            #goes to the choices and picks one
                ##if it is the last value, goes to the previous value
                ###This is the problem
            if A[j,k]==choices[j][k][-1]:
                last_one=choices[j][k][-1]
                place=A[j,k]
            ##go through each of the previous values, if they are the last value of the choice martix then set it to 0 and go the the next previous location and do the same check
                while place==last_one:
                    A[j,k]=0
                    cur=cur-1
                    if cur==-1:
                        return "No Solution",iterat
                    j=int(to_start[cur][0][0])
                    k=int(to_start[cur][0][1])
                    ##last_one is the last choice in the choice martix of that location
                    last_one=choices[j][k][-1]
                    place=A[j,k]
                #reset the ulitity function because we went backwards
                U=UTILITYFUNCT(A,lettersdict,lettersCURRENT)
                ind=(choices[j][k]).index(A[j,k])
                A[j,k]=choices[j][k][ind+1]
               
            #if the value is 0 set it to the first choice
            elif A[j,k]==0:
                A[j,k]=choices[j][k][0]
            #if the value is not zero and the last value, go to the next choice
            else:
                ind=(choices[j][k]).index(A[j,k])
                A[j,k]=choices[j][k][ind+1]
            UA=UTILITYFUNCT(A,lettersdict,lettersCURRENT)
            #if utility function improved, kept it 
            if UA<=U:
                U=UA
                CURRENT=A
                if cur<len(to_start)-1:
                    cur=cur+1

In [157]:
letters_array,solutions,letters_dict=setup("sampleData_3_fail.txt")

In [158]:
print(min_conflicts(letters_dict,letters_array))

('No Solution', 22)


In [151]:
letters_array,solutions,letters_dict=setup("sampleData_4.txt")

In [152]:
print(min_conflicts(letters_dict,letters_array))

(array([[4, 1, 3, 2],
       [3, 2, 1, 4],
       [1, 4, 2, 3],
       [2, 3, 4, 1]]), 97)


In [153]:
letters_array,solutions,letters_dict=setup("sampleData_5.txt")

In [154]:
print(min_conflicts(letters_dict,letters_array))

(array([[5, 3, 4, 1, 2],
       [3, 5, 1, 2, 4],
       [1, 4, 2, 5, 3],
       [2, 1, 3, 4, 5],
       [4, 2, 5, 3, 1]]), 396)


In [155]:
letters_array,solutions,letters_dict=setup("sampleData_6.txt")

In [156]:
print(min_conflicts(letters_dict,letters_array))

(array([[5, 6, 3, 4, 1, 2],
       [6, 1, 4, 5, 2, 3],
       [4, 5, 2, 3, 6, 1],
       [3, 4, 1, 2, 5, 6],
       [2, 3, 6, 1, 4, 5],
       [1, 2, 5, 6, 3, 4]]), 3368)
