# LOCAL SEARCH

In [3]:
import random
import numpy as np
import itertools
from functions import *
import time

## Utility function and Min-conflicts algorithm

I mainly changed the else statemnt in min_conflicts
but I also changed the parameter orders because it was confusing me

In [69]:
#OUT UTILITY FUNCTION DEFINED BY U=R+C+L
#R->NUMBER OF ROWS WITH EQUAL NUMBERS
#C->NUMBER OF COLUMNS WITH EQUAL NUMBERS
#Z-> number of zeros
#L->NUMBER OF LOCATIONS THAT DON'T SATISFY THE LETTER RESTRICTION
def UTILITYFUNCT(B,lettersdict,lettersB):
    N=np.shape(B)[0]
    R=0
    C=0
    L=0
    Z=0
    for i in range(N):
        for j in range(N):
            if not check_no_zero([i,j],B):
                Z=Z+1
    for i in range(N):
        if not row_checker(i,B):
            R=R+1
    for j in range(N):
        if not column_checker(j,B):
            C=C+1
    for i in range(N):
        for j in range(N):
            if not letter_check([i,j],B,lettersB,lettersdict):
                L=L+1
    U=R+C+L+Z
    return U
#INPUTS: INITIAL MATRIX CURRENT, LETTERS OF THE CURRENT,LETTERS DIC AND MAXIMUM ALLOWED NUMBER OF STEPS
def MIN_CONFLICTS(lettersdict,lettersCURRENT):
    dim=len(lettersCURRENT)
    CURRENT=np.array([[0]*dim for i in range(dim)])
    choices,to_start=get_choices_letters(CURRENT,lettersdict)
    #CURRENT is the VALUES OF THE MATRIX
    iterat=0
    for row in range(0,len(choices)):
        for col in range(0,len(choices)):
            CURRENT[row,col]=0
    #UTILITY FUNCTION U
    A=CURRENT
    U=UTILITYFUNCT(CURRENT,lettersdict,lettersCURRENT)
    UA=U
    # is the value at the most constranted location 
    cur=0

    while True:
        iterat=iterat+1
        if U==0:
            return CURRENT,iterat
        else:
            ###main changes
            j=int(to_start[cur][0][0])
            k=int(to_start[cur][0][1])
            A=CURRENT
            #goes to the choices and picks one
                ##if it is the last value, goes to the previous value
                ###This is the problem
            if A[j,k]==choices[j][k][-1]:
                last_one=choices[j][k][-1]
                place=A[j,k]
            ##go through each of the previous values, if they are the last value of the choice martix then set it to 0 and go the the next previous location and do the same check
                while place==last_one:
                    #choices=add_location_possibilites(row,column,choices,matrix,letter_dict,letter_array)
                    A[j,k]=0
                    cur=cur-1
                    if cur==-1:
                        return "No Solution",A,iterat
                    j=int(to_start[cur][0][0])
                    k=int(to_start[cur][0][1])
                    ##last_one is the last choice in the choice martix of that location
                    last_one=choices[j][k][-1]
                    place=A[j,k]
            elif A[j,k]==0:
                A[j,k]=choices[j][k][0]
            else:
                ind=(choices[j][k]).index(A[j,k])
                A[j,k]=choices[j][k][ind+1]
            UA=UTILITYFUNCT(A,lettersdict,lettersCURRENT)
            #if utility function improved, kept it 
            if UA<U:
                U=UA
                CURRENT=A
                cur=cur+1
                print(A)
                
                
                        

In [70]:
letters_array,solutions,letters_dict=setup("sampleData_3.txt")

In [71]:
print(MIN_CONFLICTS(letters_dict,letters_array))

[[0 0 0]
 [0 0 0]
 [0 0 2]]
[[1 0 0]
 [0 0 0]
 [0 0 2]]
[[1 0 0]
 [2 0 0]
 [0 0 2]]
[[1 0 0]
 [2 1 0]
 [0 0 2]]
[[1 0 0]
 [2 1 3]
 [0 0 2]]
[[1 0 0]
 [2 1 3]
 [3 0 2]]
('No Solution', array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]), 16)


In [13]:
dim=len(solutions)
solutions=np.array([[1]*dim for i in range(dim)])
#solution starts as 1s
MIN_CONFLICTS(solutions,letters_dict,letters_array)

(array([[1, 2, 3],
        [2, 3, 1],
        [3, 1, 2]]), 11728)

In [3]:
start=time.time()
lettersA,A,lettersdict=setup("sampleData_3.txt")
# FIRST ASSIGNMENT
m,n=np.shape(A)
max_steps=10**4
#THIS IS JUST FOR CREATING THE FIRST INITIAL MATRIX WITH ALL NUMBERS DIFFERENT IN EACH ROW
v=[i for i in range(1,n+1)]
perm=list(itertools.permutations(v))
L=len(perm)
#We start with different numbers in each row
for i in range(m):
        A[i]=perm[random.randint(0,L)]
#UTILITY FUNCTION: U=R+C+L; R=ROWS REPEATED,C=COLUMNS REPEATED, L=NUMBER OF LETTERS WHO DON'T GET THE RESULT
# We want obtain 0 in this function
U=1000000;
if check_all(A,lettersA,lettersdict):
    print(A, 'is the solution for the problem')
else:
    print(A,'is not the solution for the problem')
U0=UTILITYFUNCT(A,lettersdict,lettersA)    
print("the initial utility function is",U0)
MIN_CONFLICTS(A,lettersA,lettersdict,max_steps)
finish=time.time()-start
print("the time of execution was",finish)

[[1 2 3]
 [3 1 2]
 [1 3 2]] is not the solution for the problem
the initial utility function is 6
[[1 2 1]
 [1 1 3]
 [2 1 3]] is the solution for the problem
the time of execution was 2.213440179824829
