# LOCAL SEARCH

In [1]:
import random
import numpy as np
import itertools
from functions import *
import time

## Utility function and Min-conflicts algorithm

I mainly changed the else statemnt in min_conflicts
but I also changed the parameter orders because it was confusing me

In [14]:
#OUT UTILITY FUNCTION DEFINED BY U=R+C+L
#R->NUMBER OF ROWS WITH EQUAL NUMBERS
#C->NUMBER OF COLUMNS WITH EQUAL NUMBERS
#L->NUMBER OF LOCATIONS THAT DON'T SATISFY THE LETTER RESTRICTION
def UTILITYFUNCT(B,lettersdict,lettersB):
    N=np.shape(B)[0]
    R=0
    C=0
    L=0
    for i in range(N):
        if not row_checker(i,B):
            R=R+1
    for j in range(N):
        if not column_checker(j,B):
            C=C+1
    for i in range(N):
        for j in range(N):
            if not letter_check([i,j],B,lettersB,lettersdict):
                L=L+1
    U=R+C+L 
    return U
#INPUTS: INITIAL MATRIX CURRENT, LETTERS OF THE CURRENT,LETTERS DIC AND MAXIMUM ALLOWED NUMBER OF STEPS
def MIN_CONFLICTS(lettersdict,lettersCURRENT):    
    #CURRENT is the VALUES OF THE MATRIX
    CURRENT=np.array([[1]*dim for i in range(dim)])
    iterat=0
    N,M=np.shape(CURRENT)
    A=CURRENT
    #UTILITY FUNCTION U
    U=UTILITYFUNCT(CURRENT,lettersdict,lettersCURRENT)
    UA=U
    while True:
        iterat=iterat+1
        if U==0:
            return CURRENT,iterat
        else:
            ###main changes
            #randomly pick a location
            j=random.randint(0,len(A)-1)
            k=random.randint(0,len(A)-1)
            A=CURRENT
            #add one to the location if it is less than the max value, if equal to max value, set it to 1
            if A[j,k]==len(A):
                A[j,k]=1
            else:
                A[j,k]=A[j,k]+1
            UA=UTILITYFUNCT(A,lettersdict,lettersCURRENT)
            #if utility function improved, kept it 
            if UA<U:
                U=UA
                CURRENT=A
                        
                    
    print("THE ALGORITHM DID NOT FIND THE FINAL SOLUTION AFTER", maxsteps, "ITERATIONS")
    print("THE FINAL UTILITY FUNCTION WAS",U,"WITH MATRIX",CURRENT)
    

In [15]:
letters_array,solutions,letters_dict=setup("sampleData_3.txt")

In [19]:

MIN_CONFLICTS(letters_dict,letters_array)

(array([[1, 2, 3],
        [2, 3, 1],
        [3, 1, 2]]), 35668)

In [5]:
dim=len(solutions)
solutions=np.array([[1]*dim for i in range(dim)])
#solution starts as 1s
MIN_CONFLICTS(solutions,letters_dict,letters_array)

(array([[1, 2, 3],
        [2, 3, 1],
        [3, 1, 2]]), 301)

In [3]:
start=time.time()
lettersA,A,lettersdict=setup("sampleData_3.txt")
# FIRST ASSIGNMENT
m,n=np.shape(A)
max_steps=10**4
#THIS IS JUST FOR CREATING THE FIRST INITIAL MATRIX WITH ALL NUMBERS DIFFERENT IN EACH ROW
v=[i for i in range(1,n+1)]
perm=list(itertools.permutations(v))
L=len(perm)
#We start with different numbers in each row
for i in range(m):
        A[i]=perm[random.randint(0,L)]
#UTILITY FUNCTION: U=R+C+L; R=ROWS REPEATED,C=COLUMNS REPEATED, L=NUMBER OF LETTERS WHO DON'T GET THE RESULT
# We want obtain 0 in this function
U=1000000;
if check_all(A,lettersA,lettersdict):
    print(A, 'is the solution for the problem')
else:
    print(A,'is not the solution for the problem')
U0=UTILITYFUNCT(A,lettersdict,lettersA)    
print("the initial utility function is",U0)
MIN_CONFLICTS(A,lettersA,lettersdict,max_steps)
finish=time.time()-start
print("the time of execution was",finish)

[[1 2 3]
 [3 1 2]
 [1 3 2]] is not the solution for the problem
the initial utility function is 6
[[1 2 1]
 [1 1 3]
 [2 1 3]] is the solution for the problem
the time of execution was 2.213440179824829
