# LOCAL SEARCH

In [3]:
import random
import numpy as np
import itertools
from functions import *
import time

## Utility function and Min-conflicts algorithm

In [4]:
#OUT UTILITY FUNCTION DEFINED BY U=R+C+L
#R->NUMBER OF ROWS WITH EQUAL NUMBERS
#C->NUMBER OF COLUMNS WITH EQUAL NUMBERS
#L->NUMBER OF LOCATIONS THAT DON'T SATISFY THE LETTER RESTRICTION
def UTILITYFUNCT(B,lettersdict,lettersB):
    N=np.shape(B)[0]
    R=0
    C=0
    L=0
    for i in range(N):
        if not row_checker(i,B):
            R=R+1
    for j in range(N):
        if not column_checker(j,B):
            C=C+1
    for i in range(N):
        for j in range(N):
            if not letter_check([i,j],B,lettersB,lettersdict):
                L=L+1
    U=R+C+L 
    return U
#INPUTS: INITIAL MATRIX CURRENT, LETTERS OF THE CURRENT,LETTERS DIC AND MAXIMUM ALLOWED NUMBER OF STEPS
def MIN_CONFLICTS(CURRENT,lettersCURRENT,lettersdic,maxsteps):    
    #CURRENT is the VALUES OF THE MATRIX
    iterat=0
    N,M=np.shape(CURRENT)
    A=CURRENT
    #UTILITY FUNCTION U
    U=UTILITYFUNCT(CURRENT,lettersdict,lettersCURRENT)
    UA=U
    for i in range(maxsteps):
        iterat=iterat+1
        if U==0:
            print(CURRENT, 'is the solution for the problem')
            return CURRENT,iterat
        else:
            #RANDOM NUMBERS FOR EACH VARIABLE
            for j in range(N):
                for k in range(N):
                    A=CURRENT
                    A[j,k]=random.randint(1,N)
                    UA=UTILITYFUNCT(A,lettersdic,lettersCURRENT)
                    if UA<U:
                        U=UA
                        CURRENT=A
                        
                    
    print("THE ALGORITHM DID NOT FIND THE FINAL SOLUTION AFTER", maxsteps, "ITERATIONS")
    print("THE FINAL UTILITY FUNCTION WAS",U,"WITH MATRIX",CURRENT)
    

In [8]:
start=time.time()
lettersA,A,lettersdict=setup("sampleData.txt")
# FIRST ASSIGNMENT
m,n=np.shape(A)
max_steps=10**4
#THIS IS JUST FOR CREATING THE FIRST INITIAL MATRIX WITH ALL NUMBERS DIFFERENT IN EACH ROW
v=[i for i in range(1,n+1)]
perm=list(itertools.permutations(v))
L=len(perm)
#We start with different numbers in each row
for i in range(m):
        A[i]=perm[random.randint(0,L)]
#UTILITY FUNCTION: U=R+C+L; R=ROWS REPEATED,C=COLUMNS REPEATED, L=NUMBER OF LETTERS WHO DON'T GET THE RESULT
# We want obtain 0 in this function
U=1000000;
if check_all(A,lettersA,lettersdict):
    print(A, 'is the solution for the problem')
else:
    print(A,'is not the solution for the problem')
U0=UTILITYFUNCT(A,lettersdict,lettersA)    
print("the initial utility function is",U0)
MIN_CONFLICTS(A,lettersA,lettersdict,max_steps)
finish=time.time()-start
print("the time of execution was",finish)

[[1 5 4 2 3 6]
 [6 5 3 2 1 4]
 [5 1 4 2 3 6]
 [1 2 4 6 5 3]
 [2 3 6 4 5 1]
 [6 4 2 1 3 5]] is not the solution for the problem
the initial utility function is 38


KeyboardInterrupt: 